# use an official node.js runtime as a parent image
FROM node:22-alpine

#set working directory in container
WORKDIR /app

#copy package.json and package-lock.json into container
COPY package*.json .

#install the dependencies:
RUN npm install

#copy rest of the application code (source--todoApp  ----> destination--/app)
COPY . .

#expose the port that the app run on: (tell network to open up this port to incoming request)
EXPOSE 5000

# Define the command to run application:
CMD [ "node","./src/server.js" ]
